# -*- coding: utf-8 -*-
"""Projeto_01_Detetive.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z2wCjSXsNu0fR3MeUQUha8osxiiucVfs

Esse projeto tem a finalidade de fixar os conhecimentos de Variáveis, Print, Input e Condicionais, para isso crie um programa que faça 5 perguntas para uma 
pessoa sobre um crime. As perguntas são:</br>
• "Você telefonou para a vítima?"</br>
• " Você esteve no local do crime?"</br>
• " Você mora perto da vítima?"</br>
• " Você devia para a vítima?"</br>
• " Você já trabalhou com a vítima?" </br>
O programa deve, no final, emitir uma classificação sobre a participação da 
pessoa no crime.</br>
Se a pessoa responder positivamente a:</br>
• 2 questões ela deve ser classificada como "Suspeita",</br>
• Entre 3 e 4 como "Cúmplice"</br>
• 5 como "Assassino". </br>
• Caso contrário, ele será classificado como "Inocente".</br>
O projeto deve ser feito individualmente e entregue até o final da aula 06
"""

print("=-=" * 10)
print(" " * 4,"PROJETO 01 - DETETIVE")
print("=-=" * 10)
cont = 0
traco = "-" * 30
resp1 = input("Você telefonou para a vítima?\n[S/N] ")
if resp1.lower().strip()[0] == "s": cont = cont + 1
print(traco)
resp2 = input("Você esteve no local do crime?\n[S/N] ")
if resp2.lower().strip()[0] == "s": cont = cont + 1
print(traco)
resp3 = input("Você mora perto da vítima?\n[S/N] ")
if resp3.lower().strip()[0] == "s": cont = cont + 1
print(traco)
resp4 = input("Você devia para a vítima?\n[S/N] ")
if resp4.lower().strip()[0] == "s": cont = cont + 1
print(traco)
resp5 = input("Você já trabalhou com a vítima?\n[S/N] ")
if resp5.lower().strip()[0] == "s": cont = cont + 1
print(traco)
resul = "Classificação: "
if cont == 2:
  resul = resul + "Suspeito(a)"
elif 3 <= cont <=4:
  resul = resul + "Cúmplice"
elif cont == 5:
  resul = resul + "Assassino(a)"
else:
  resul = resul + "Inocente"
print(resul)
print("=-=" * 10)
print(" " * 7, "CASO ENCERRADO!")
print("=-=" * 10)